services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: nguyenthanhduyofficial
      POSTGRES_PASSWORD: nguyenthanhduyofficial
      POSTGRES_DB: postgres_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nguyenthanhduyofficial_nettwork

volumes:
  postgres_data:

networks:
  nguyenthanhduyofficial_nettwork:
